-- 코드를 입력하세요
SELECT C.YEAR, C.MONTH, C.GENDER, COUNT(*) AS USERS
FROM (
    SELECT
        YEAR(B.SALES_DATE) AS YEAR,
        MONTH(B.SALES_DATE) AS MONTH,
        GENDER,
        COUNT(*) AS USERS
    FROM USER_INFO A
        JOIN ONLINE_SALE B
        ON A.USER_ID = B.USER_ID
    WHERE GENDER IS NOT NULL
    GROUP BY YEAR, MONTH, GENDER, A.USER_ID
    ) C
GROUP BY C.YEAR, C.MONTH, C.GENDER
ORDER BY C.YEAR, C.MONTH, C.GENDER