-- 코드를 입력하세요
SELECT
    B.FOOD_TYPE,
    B.REST_ID,
    B.REST_NAME,
    B.FAVORITES
FROM (
    SELECT
        REST_ID,
        RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS "RANK"
    FROM REST_INFO) A
JOIN REST_INFO B
USING(REST_ID)
WHERE A.RANK = 1
ORDER BY FOOD_TYPE DESC
