-- 코드를 입력하세요
WITH 
USER_INFO_2021 AS (
    SELECT *
    FROM USER_INFO
    WHERE YEAR(JOINED)=2021
), 
TMP AS (
    SELECT
        YEAR(SALES_DATE) AS YEAR,
        MONTH(SALES_DATE) AS MONTH,
        COUNT(DISTINCT B.USER_ID) AS CNT
    FROM USER_INFO_2021 A
    JOIN ONLINE_SALE B
    ON A.USER_ID=B.USER_ID
    GROUP BY YEAR, MONTH
)

SELECT 
    A.YEAR,
    A.MONTH,
    A.CNT AS PUCHASED_USERS,
    ROUND(A.CNT/B.TOTAL, 1) AS PUCHASED_RATIO
FROM TMP A, (SELECT COUNT(*) AS TOTAL FROM USER_INFO_2021) B
WHERE A.YEAR IS NOT NULL
ORDER BY YEAR, MONTH