-- 코드를 입력하세요
WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM CTE
    WHERE HOUR!=23
)

SELECT 
    A.HOUR,
    COUNT(B.DATETIME) AS COUNT
FROM CTE A
LEFT OUTER JOIN ANIMAL_OUTS B
ON A.HOUR = HOUR(B.DATETIME)
GROUP BY A.HOUR
ORDER BY A.HOUR
