-- 코드를 입력하세요
SELECT 
    B.CATEGORY,
    B.PRICE AS MAX_PRICE,
    B.PRODUCT_NAME
FROM (
    SELECT
        PRODUCT_ID,
        RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS "RANK"
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')) A
JOIN FOOD_PRODUCT B
USING(PRODUCT_ID)
WHERE A.RANK = 1
ORDER BY MAX_PRICE DESC