-- 코드를 입력하세요
SELECT 
    RI.REST_ID,
    RI.REST_NAME,
    RI.FOOD_TYPE,
    RI.FAVORITES,  
    RI.ADDRESS,
    ROUND(AVG(RR.REVIEW_SCORE), 2) as SCORE
FROM 
    REST_INFO RI
    JOIN REST_REVIEW RR
    ON RI.REST_ID = RR.REST_ID
WHERE RI.ADDRESS LIKE '%서울%'
GROUP BY RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS
ORDER BY SCORE DESC, RI.FAVORITES DESC;


SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, C.SCORE
FROM REST_INFO AS A
JOIN (SELECT B.REST_ID, ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE
      FROM REST_REVIEW AS B
      GROUP BY B.REST_ID) AS C
ON A.REST_ID = C.REST_ID
AND A.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, A.FAVORITES DESC